# Site settings
title: Brian Levy 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.brian-levy.com" # the base hostname & protocol for your site
twitter_username: evilbryan
instagram_username: briandlevy
github_username:  
proj-imgpath: /img/projects/

# Build settings
markdown: kramdown
exclude: [
	.gitignore,
	svg-icons,
	svg-decorations,
	scss,
	.sass-cache,
	package.json,
	Gruntfile.js,
	node_modules,
	readme.md
]